#!/usr/bin/env bash

modified_files_n=0
while IFS= read line
do
    echo "$line"
    modified_files[ $modified_files_n ]="$line"
    (( modified_files_n++ ))
done < <(git status --porcelain)

function find_modified_file {
    local i=0
    while [[ $i < $modified_files_n ]]; do
        if [ "${modified_files[ $i ]:3}" == "$1" ]; then
            echo "${modified_files[ $i ]}"
            return 0
        fi
        (( i++ ))
    done
    return 1
}

git ls-files | while read -r filepath ; do
    filestatus=$(find_modified_file "$filepath")
    if [[ $? ]]; then
        filestatus="   $filepath"
    fi
    echo "$filestatus"
done
