#!/usr/bin/env bash

declare -A FILE_STATUS

while IFS= read line; do
    status=${line:0:2}
    file=${line:3}
    FILE_STATUS[$file]="$status"
done < <(git status --porcelain)

while IFS= read line; do
    if [ ! ${FILE_STATUS[$line]+_} ]; then
        FILE_STATUS[$line]="  "
    fi
done < <(git ls-files)

files_sorted=( $(
    for file in "${!FILE_STATUS[@]}"; do
        echo "$file"
    done | sort)
)

for file in "${files_sorted[@]}"; do
    echo "${FILE_STATUS[$file]} $file"
done
